[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core>=1" ]

[project]
name = "pydjantic"
version = "1.1.5"
description = "Pydantic Settings for Django"
readme = "README.md"
keywords = [ "django", "pydantic", "PydanticSettings", "settings" ]
license = "MIT"
license-files = [
    "LICENSE",
]

authors = [ { name = "Vladimir Vyazovetskov", email = "erhosen@gmail.com" } ]
requires-python = ">=3.9,<3.12"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    # The only Django version that supports both Python 3.9 and 3.10 is Django 4
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    # Python version 3.11 should be backwards compatible enough to work with Django 4
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "dj-database-url (>=2.1,<2.2)",
    "pydantic (>=2.5.2,<2.6)",
    "pydantic-settings (>=2.1,<2.2)"
]
urls.homepage = "https://github.com/ErhoSen/pydjantic"
urls.repository = "https://github.com/ErhoSen/pydjantic"

[dependency-groups]
dev = [
    "deepdiff (>=5.8.1,<5.9)",
    "pre-commit (>=2.11.1,<2.22)",
    "pytest (>=6.2.2,<6.3)",
    "pytest-cov (>=2.11.1,<2.13)",
    "tempenv (>=2,<2.1)"
]
