[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core>=1" ]

[project]
name = "pydjantic"
version = "1.1.5"
description = "Pydantic Settings for Django"
authors = [ { name = "Vladimir Vyazovetskov", email = "erhosen@gmail.com" } ]
license = "MIT"
readme = "README.md"
urls.homepage = "https://github.com/ErhoSen/pydjantic"
urls.repository = "https://github.com/ErhoSen/pydjantic"
keywords = [ "pydantic", "django", "PydanticSettings", "settings" ]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Other Environment",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
license-files = [
  "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
dj-database-url = ">=2.1.0,<2.2"
pydantic = ">=2.5.2,<2.6"
pydantic-settings = ">=2.1.0,<2.2"

[tool.poetry.group.dev.dependencies]
pytest = ">=6.2.2,<6.3"
pytest-cov = ">=2.11.1,<2.13"
pre-commit = ">=2.11.1,<2.22"
tempenv = ">=2.0.0,<2.1"
deepdiff = ">=5.8.1,<5.9"
